<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TimeOut.aspx.cs" Inherits="EventCheckIn.TimeOut" %>

<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-svg lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]><html class="no-svg lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]><html class="no-svg lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--><html lang="en"><!--<![endif]-->

<head id="Head1" runat="server">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="keywords" content="WSU, Washington State, Washington State University " />
	<meta charset="utf-8">
    <title>Kiosk | ASCC</title>
    
	<!-- FAVICON -->
	<link rel="shortcut icon" href="https://repo.wsu.edu/spine/1/favicon.ico" />

	<!-- STYLESHEETS -->
	<link href="https://repo.wsu.edu/spine/1/spine.min.css" rel="stylesheet" type="text/css" />
	<!-- Your custom stylesheets here -->
    <link rel="stylesheet" type="text/css" href="style.css"/>

	<!-- RESPOND -->
	<meta name="viewport" content="width=device-width, user-scalable=yes">

	<!-- SCRIPTS -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
	<script src="https://repo.wsu.edu/spine/1/spine.min.js"></script>

    <!--Time out scripts-->
    <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
    <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/jquery-ui.min.js"></script>
    <script type="text/javascript" src="Scripts/timeout.js"></script>

	<!-- COMPATIBILITY -->
	<!--[if lt IE 9]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	<noscript><style>#spine .spine-sitenav ul ul li { display: block !important; }</style></noscript>

	<!-- DOCS -->
	<link type="text/plain" rel="author" href="https://repo.wsu.edu/spine/1/authors.txt">
	<link type="text/html" rel="help" href="https://brand.wsu.edu">

	<!-- ANALYTICS -->

</head>

<body class="">

<!-- WRAPPING -->
<div id="jacket">
<div id="binder" class="hybrid">
<!-- GRID BEHAVIOR: Default behavior can be changed by changing "hybrid" to "fixed" or "fluid". -->
<!-- CONTENT -->
    
    <form id="form2" runat="server">
        <div class="page" id="pagecontainer"> <!-- For time out -->
            <main>
                <div id="header">
                    <h6>Academic Success and Career Center</h6>
                    <h1>Kiosk</h1>
                </div>

                <div id="body">
	            <!-- Responsive Sections -->
		        <section class="row single guttered marginalize-ends">
                    <div class="column one">
                        <br />
		     
	                </div><!--/column-->

	            <%--<div class="column two">

		            <aside>
				            <h2>Sidebar</h2>
				            <ul>
					            <li>Fight, fight, fight for Washington State! Win the victory!</li>
					            <li>Win the day for Crimson and Gray! Best in the West, we know you'll all do your best, so</li>
					            <li>On, on, on, on! Fight to the end! Honor and Glory you must win! So</li>
					            <li>Fight, fight, fight for Washington State and victory!</li>
					            <li>W-A-S-H-I-N-G-T-O-N-S-T-A-T-E-C-O-U-G-S! <strong>GO COUGS!!</strong></li>
				            </ul>
				            <small>The song appears in the 1985 film <i>Volunteers</i>, sung by John Candy's character Tommy Tuttle from Tacoma, Washington, and later used as a war cry by the Communists.</small>
		            </aside>

	            </div><!--/column-->--%>
		        </section>
                </div>
            </main>
        </div> <!-- pagecontainer -->
    </form>
<!-- /CONTENT -->

<!-- SPINE -->
<div id="spine" class="spine-column shelved bleed dark">
<!-- SPINE COLOR: Available spine colors are crimson, gray, gray-lightest, gray-lightly, gray-lighter, gray-light, gray-dark, gray-darker, gray-darkest. Replace the color class above with your preferred color if you want to override the default. -->
<!-- SPINE BLEED: Remove "bleed" so that  -->
<div id="glue" class="spine-glue">

<header class="spine-header">
	<a href="http://www.wsu.edu/" id="wsu-signature" class="spine-signature">Washington State University</a>
</header>

<!-- ACTIONS -->
<section id="wsu-actions" class="spine-actions">

	<!-- Tabs -->
	<ul id="wsu-actions-tabs" class="spine-actions-tabs clearfix">
		<%--<li id="wsu-search-tab" class="spine-search-tab closed"><button>Search</button></li>--%>
		<li id="wsu-contact-tab" class="spine-contact-tab closed"><button>Contact</button></li>
		<%--<li id="wsu-share-tab" class="spine-share-tab closed"><button>Share</button></li>--%>
		<li id="wsu-print-tab" class="spine-print-tab closed"><button>Print</button></li>
	</ul>

	<!-- Actions generated by spine.js end up here -->
</section><!--/#wsu-actions-->

<section id="spine-navigation" class="spine-navigation">
	<nav class="spine-sitenav">    
        <ul>
			<!-- 
			NAVIGATION: Your navigation list here
			• Active link should be denoted with an "active" or "current" link on the link's parent li element.
			• First link should be a home link (otherwise, in exceptional cases, add "homeless" class to #site nav)-->

            <!--Need id and runat for li for adding "current" class for each page at code behind-->

			<li><a href="http://ascc.wsu.edu">ASCC</a></li>

            <!--<li><a href="">Options</a>
				<ul>
					<li><a href="http://brand.wsu.edu/media/web/">The WSU Web Template</a></li>
					<li><a href="http://brand.wsu.edu/media/web/web-standards">Spine standards</a></li>
				</ul>
			</li>-->
         </ul>
	</nav>

	<%--<nav class="spine-offsitenav">
	<ul>
		<li><a href="http://www.example.com">Offsite Link</a></li>
		<li><a href="http://fonts.wsu.edu">Another</a></li>
	</ul>
</nav>--%>

</section><!-- #navigation -->

<!-- Social and Global Links -->
<footer class="spine-footer">
	<nav id="wsu-social-channels" class="spine-social-channels">
		<!--
		SOCIAL CHANNELS: You can replace default social channels with your own. Available channels are:
		• Facebook, Twitter, Youtube, Google+ (.googleplus-channel), Tumblr, Pinterest, Flickr, 
		• Example: <li class="pinterest-channel"><a href="http://pinterest.com/user">Pinterest</a></li>
		• Maximum number of channels is five -->
		<ul>
			<li class="facebook-channel"><a href="https://www.facebook.com/ascc.wsu">Facebook</a></li>
			<li class="twitter-channel"><a href="https://twitter.com/ASCC_WSU">Twitter</a></li>
			<%--<li class="youtube-channel"><a href="http://www.youtube.com/washingtonstateuniv">YouTube</a></li>--%>
            <li class="pinterest-channel"><a href="http://www.pinterest.com/wsuascc/">Pinterest</a></li>
			<%--<li class="directory-channel"><a href="http://social.wsu.edu">Directory</a></li>--%>
		</ul>
	</nav>
	<nav id="wsu-global-links" class="spine-global-links">
		<ul>
			<li class="mywsu-link"><a href="http://my.wsu.edu/">myWSU</a></li>
			<li class="access-link"><a href="http://access.wsu.edu/">Access</a></li>
			<li class="policies-link"><a href="http://policies.wsu.edu/">Policies</a></li>
			<li class="copyright-link"><a href="http://copyright.wsu.edu">&copy;</a></li>
		</ul>
	</nav>	
</footer>

</div><!--/glue-->
</div><!--/spine-->
    
<!-- /SPINE -->

</div><!--/cover-->
</div><!--/jacket-->
<!-- /WRAPPING -->

<div id="contact-details" itemscope itemtype="http://schema.org/Organization"> 
	<span itemprop="department"  content="Academic Success and Career Center"></span> 
	<span itemprop="name" content="Washington State University"></span> 
	<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
		<!--<span itemprop="location" content="Lighty Student Services Building Room 180"></span>-->
		<span itemprop="streetAddress" content="Lighty Student Services Building Room 180"></span>
		<span itemprop="addressLocality" content="Pullman"></span>
		<span itemprop="addressRegion" content="WA"></span>
		<span itemprop="postalCode" content="99163"></span>
	</div>
	<span itemprop="telephone" content="509-335-6000"></span>
	<span itemprop="email" content="ascc@wsu.edu"></span>
	<!--<span itemprop="contactPoint" content="http://ascc.wsu.edu/"></span>-->
	<span itemprop="url" content="http://ascc.wsu.edu/"></span>
</div>

</body>
</html>