//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EventCheckIn.edu.wsu.aiswebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSUADAuthenticateUser_WSSoap", Namespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS")]
    public partial class WSUADAuthenticateUser_WS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WSUAuthenticateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSUAuthenticateUserGetADIdentityAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSUAuthenticateUserGetADGroupMembershipsOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSUAuthenticateUserIsInAnyADGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSUAuthenticateUserIsInAllADGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSUAuthenticateUserGetAnyGivenADAttributesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSUADAuthenticateUser_WS() {
            this.Url = global::EventCheckIn.Properties.Settings.Default.EventCheckIn_edu_wsu_aiswebservice_WSUADAuthenticateUser_WS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WSUAuthenticateUserCompletedEventHandler WSUAuthenticateUserCompleted;
        
        /// <remarks/>
        public event WSUAuthenticateUserGetADIdentityAttributesCompletedEventHandler WSUAuthenticateUserGetADIdentityAttributesCompleted;
        
        /// <remarks/>
        public event WSUAuthenticateUserGetADGroupMembershipsCompletedEventHandler WSUAuthenticateUserGetADGroupMembershipsCompleted;
        
        /// <remarks/>
        public event WSUAuthenticateUserIsInAnyADGroupsCompletedEventHandler WSUAuthenticateUserIsInAnyADGroupsCompleted;
        
        /// <remarks/>
        public event WSUAuthenticateUserIsInAllADGroupsCompletedEventHandler WSUAuthenticateUserIsInAllADGroupsCompleted;
        
        /// <remarks/>
        public event WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsCompletedEventHandler WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsCompleted;
        
        /// <remarks/>
        public event WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsCompletedEventHandler WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsCompleted;
        
        /// <remarks/>
        public event WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsCompletedEventHandler WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsCompleted;
        
        /// <remarks/>
        public event WSUAuthenticateUserGetAnyGivenADAttributesCompletedEventHandler WSUAuthenticateUserGetAnyGivenADAttributesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS/WSUAuthentica" +
            "teUser", RequestNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", ResponseNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSUAuthenticateUserReturnObj WSUAuthenticateUser(string strUserName, string strUserPassword) {
            object[] results = this.Invoke("WSUAuthenticateUser", new object[] {
                        strUserName,
                        strUserPassword});
            return ((WSUAuthenticateUserReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserAsync(string strUserName, string strUserPassword) {
            this.WSUAuthenticateUserAsync(strUserName, strUserPassword, null);
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserAsync(string strUserName, string strUserPassword, object userState) {
            if ((this.WSUAuthenticateUserOperationCompleted == null)) {
                this.WSUAuthenticateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSUAuthenticateUserOperationCompleted);
            }
            this.InvokeAsync("WSUAuthenticateUser", new object[] {
                        strUserName,
                        strUserPassword}, this.WSUAuthenticateUserOperationCompleted, userState);
        }
        
        private void OnWSUAuthenticateUserOperationCompleted(object arg) {
            if ((this.WSUAuthenticateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSUAuthenticateUserCompleted(this, new WSUAuthenticateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS/WSUAuthentica" +
            "teUserGetADIdentityAttributes", RequestNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", ResponseNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSUAuthenticateUserGetADIdentityAttributesReturnObj WSUAuthenticateUserGetADIdentityAttributes(string strUserName, string strUserPassword) {
            object[] results = this.Invoke("WSUAuthenticateUserGetADIdentityAttributes", new object[] {
                        strUserName,
                        strUserPassword});
            return ((WSUAuthenticateUserGetADIdentityAttributesReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserGetADIdentityAttributesAsync(string strUserName, string strUserPassword) {
            this.WSUAuthenticateUserGetADIdentityAttributesAsync(strUserName, strUserPassword, null);
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserGetADIdentityAttributesAsync(string strUserName, string strUserPassword, object userState) {
            if ((this.WSUAuthenticateUserGetADIdentityAttributesOperationCompleted == null)) {
                this.WSUAuthenticateUserGetADIdentityAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSUAuthenticateUserGetADIdentityAttributesOperationCompleted);
            }
            this.InvokeAsync("WSUAuthenticateUserGetADIdentityAttributes", new object[] {
                        strUserName,
                        strUserPassword}, this.WSUAuthenticateUserGetADIdentityAttributesOperationCompleted, userState);
        }
        
        private void OnWSUAuthenticateUserGetADIdentityAttributesOperationCompleted(object arg) {
            if ((this.WSUAuthenticateUserGetADIdentityAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSUAuthenticateUserGetADIdentityAttributesCompleted(this, new WSUAuthenticateUserGetADIdentityAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS/WSUAuthentica" +
            "teUserGetADGroupMemberships", RequestNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", ResponseNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSUAuthenticateUserGetADGroupMembershipsReturnObj WSUAuthenticateUserGetADGroupMemberships(string strUserName, string strUserPassword) {
            object[] results = this.Invoke("WSUAuthenticateUserGetADGroupMemberships", new object[] {
                        strUserName,
                        strUserPassword});
            return ((WSUAuthenticateUserGetADGroupMembershipsReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserGetADGroupMembershipsAsync(string strUserName, string strUserPassword) {
            this.WSUAuthenticateUserGetADGroupMembershipsAsync(strUserName, strUserPassword, null);
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserGetADGroupMembershipsAsync(string strUserName, string strUserPassword, object userState) {
            if ((this.WSUAuthenticateUserGetADGroupMembershipsOperationCompleted == null)) {
                this.WSUAuthenticateUserGetADGroupMembershipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSUAuthenticateUserGetADGroupMembershipsOperationCompleted);
            }
            this.InvokeAsync("WSUAuthenticateUserGetADGroupMemberships", new object[] {
                        strUserName,
                        strUserPassword}, this.WSUAuthenticateUserGetADGroupMembershipsOperationCompleted, userState);
        }
        
        private void OnWSUAuthenticateUserGetADGroupMembershipsOperationCompleted(object arg) {
            if ((this.WSUAuthenticateUserGetADGroupMembershipsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSUAuthenticateUserGetADGroupMembershipsCompleted(this, new WSUAuthenticateUserGetADGroupMembershipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS/WSUAuthentica" +
            "teUserIsInAnyADGroups", RequestNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", ResponseNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSUAuthenticateUserIsInAnyADGroupsReturnObj WSUAuthenticateUserIsInAnyADGroups(string strUserName, string strUserPassword, string[] strGroupsArray) {
            object[] results = this.Invoke("WSUAuthenticateUserIsInAnyADGroups", new object[] {
                        strUserName,
                        strUserPassword,
                        strGroupsArray});
            return ((WSUAuthenticateUserIsInAnyADGroupsReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserIsInAnyADGroupsAsync(string strUserName, string strUserPassword, string[] strGroupsArray) {
            this.WSUAuthenticateUserIsInAnyADGroupsAsync(strUserName, strUserPassword, strGroupsArray, null);
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserIsInAnyADGroupsAsync(string strUserName, string strUserPassword, string[] strGroupsArray, object userState) {
            if ((this.WSUAuthenticateUserIsInAnyADGroupsOperationCompleted == null)) {
                this.WSUAuthenticateUserIsInAnyADGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSUAuthenticateUserIsInAnyADGroupsOperationCompleted);
            }
            this.InvokeAsync("WSUAuthenticateUserIsInAnyADGroups", new object[] {
                        strUserName,
                        strUserPassword,
                        strGroupsArray}, this.WSUAuthenticateUserIsInAnyADGroupsOperationCompleted, userState);
        }
        
        private void OnWSUAuthenticateUserIsInAnyADGroupsOperationCompleted(object arg) {
            if ((this.WSUAuthenticateUserIsInAnyADGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSUAuthenticateUserIsInAnyADGroupsCompleted(this, new WSUAuthenticateUserIsInAnyADGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS/WSUAuthentica" +
            "teUserIsInAllADGroups", RequestNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", ResponseNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSUAuthenticateUserIsInAllADGroupsReturnObj WSUAuthenticateUserIsInAllADGroups(string strUserName, string strUserPassword, string[] strGroupsArray) {
            object[] results = this.Invoke("WSUAuthenticateUserIsInAllADGroups", new object[] {
                        strUserName,
                        strUserPassword,
                        strGroupsArray});
            return ((WSUAuthenticateUserIsInAllADGroupsReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserIsInAllADGroupsAsync(string strUserName, string strUserPassword, string[] strGroupsArray) {
            this.WSUAuthenticateUserIsInAllADGroupsAsync(strUserName, strUserPassword, strGroupsArray, null);
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserIsInAllADGroupsAsync(string strUserName, string strUserPassword, string[] strGroupsArray, object userState) {
            if ((this.WSUAuthenticateUserIsInAllADGroupsOperationCompleted == null)) {
                this.WSUAuthenticateUserIsInAllADGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSUAuthenticateUserIsInAllADGroupsOperationCompleted);
            }
            this.InvokeAsync("WSUAuthenticateUserIsInAllADGroups", new object[] {
                        strUserName,
                        strUserPassword,
                        strGroupsArray}, this.WSUAuthenticateUserIsInAllADGroupsOperationCompleted, userState);
        }
        
        private void OnWSUAuthenticateUserIsInAllADGroupsOperationCompleted(object arg) {
            if ((this.WSUAuthenticateUserIsInAllADGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSUAuthenticateUserIsInAllADGroupsCompleted(this, new WSUAuthenticateUserIsInAllADGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS/WSUAuthentica" +
            "teUserGetADIdentityAttributesGetADGroupMemberships", RequestNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", ResponseNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsReturnObj WSUAuthenticateUserGetADIdentityAttributesGetADGroupMemberships(string strUserName, string strUserPassword) {
            object[] results = this.Invoke("WSUAuthenticateUserGetADIdentityAttributesGetADGroupMemberships", new object[] {
                        strUserName,
                        strUserPassword});
            return ((WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsAsync(string strUserName, string strUserPassword) {
            this.WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsAsync(strUserName, strUserPassword, null);
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsAsync(string strUserName, string strUserPassword, object userState) {
            if ((this.WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsOperationCompleted == null)) {
                this.WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsOperationCompleted);
            }
            this.InvokeAsync("WSUAuthenticateUserGetADIdentityAttributesGetADGroupMemberships", new object[] {
                        strUserName,
                        strUserPassword}, this.WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsOperationCompleted, userState);
        }
        
        private void OnWSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsOperationCompleted(object arg) {
            if ((this.WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsCompleted(this, new WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS/WSUAuthentica" +
            "teUserGetADIdentityAttributesIsInAnyADGroups", RequestNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", ResponseNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsReturnObj WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroups(string strUserName, string strUserPassword, string[] strGroups) {
            object[] results = this.Invoke("WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroups", new object[] {
                        strUserName,
                        strUserPassword,
                        strGroups});
            return ((WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsAsync(string strUserName, string strUserPassword, string[] strGroups) {
            this.WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsAsync(strUserName, strUserPassword, strGroups, null);
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsAsync(string strUserName, string strUserPassword, string[] strGroups, object userState) {
            if ((this.WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsOperationCompleted == null)) {
                this.WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsOperationCompleted);
            }
            this.InvokeAsync("WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroups", new object[] {
                        strUserName,
                        strUserPassword,
                        strGroups}, this.WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsOperationCompleted, userState);
        }
        
        private void OnWSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsOperationCompleted(object arg) {
            if ((this.WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsCompleted(this, new WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS/WSUAuthentica" +
            "teUserGetADIdentityAttributesIsInAllADGroups", RequestNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", ResponseNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsReturnObj WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroups(string strUserName, string strUserPassword, string[] strGroups) {
            object[] results = this.Invoke("WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroups", new object[] {
                        strUserName,
                        strUserPassword,
                        strGroups});
            return ((WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsAsync(string strUserName, string strUserPassword, string[] strGroups) {
            this.WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsAsync(strUserName, strUserPassword, strGroups, null);
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsAsync(string strUserName, string strUserPassword, string[] strGroups, object userState) {
            if ((this.WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsOperationCompleted == null)) {
                this.WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsOperationCompleted);
            }
            this.InvokeAsync("WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroups", new object[] {
                        strUserName,
                        strUserPassword,
                        strGroups}, this.WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsOperationCompleted, userState);
        }
        
        private void OnWSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsOperationCompleted(object arg) {
            if ((this.WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsCompleted(this, new WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS/WSUAuthentica" +
            "teUserGetAnyGivenADAttributes", RequestNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", ResponseNamespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSUAuthenticateUserGetAnyGivenADAttributesReturnObj WSUAuthenticateUserGetAnyGivenADAttributes(string strUserName, string strUserPassword, string[] ArrayOfADAttributesToQuery) {
            object[] results = this.Invoke("WSUAuthenticateUserGetAnyGivenADAttributes", new object[] {
                        strUserName,
                        strUserPassword,
                        ArrayOfADAttributesToQuery});
            return ((WSUAuthenticateUserGetAnyGivenADAttributesReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserGetAnyGivenADAttributesAsync(string strUserName, string strUserPassword, string[] ArrayOfADAttributesToQuery) {
            this.WSUAuthenticateUserGetAnyGivenADAttributesAsync(strUserName, strUserPassword, ArrayOfADAttributesToQuery, null);
        }
        
        /// <remarks/>
        public void WSUAuthenticateUserGetAnyGivenADAttributesAsync(string strUserName, string strUserPassword, string[] ArrayOfADAttributesToQuery, object userState) {
            if ((this.WSUAuthenticateUserGetAnyGivenADAttributesOperationCompleted == null)) {
                this.WSUAuthenticateUserGetAnyGivenADAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSUAuthenticateUserGetAnyGivenADAttributesOperationCompleted);
            }
            this.InvokeAsync("WSUAuthenticateUserGetAnyGivenADAttributes", new object[] {
                        strUserName,
                        strUserPassword,
                        ArrayOfADAttributesToQuery}, this.WSUAuthenticateUserGetAnyGivenADAttributesOperationCompleted, userState);
        }
        
        private void OnWSUAuthenticateUserGetAnyGivenADAttributesOperationCompleted(object arg) {
            if ((this.WSUAuthenticateUserGetAnyGivenADAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSUAuthenticateUserGetAnyGivenADAttributesCompleted(this, new WSUAuthenticateUserGetAnyGivenADAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS")]
    public partial class WSUAuthenticateUserReturnObj {
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        private bool userIsAuthenticatedField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsAuthenticated {
            get {
                return this.userIsAuthenticatedField;
            }
            set {
                this.userIsAuthenticatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS")]
    public partial class WSUAuthenticateUserGetAnyGivenADAttributesReturnObj {
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        private bool userIsAuthenticatedField;
        
        private string[] aDAttributesReturnValueField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsAuthenticated {
            get {
                return this.userIsAuthenticatedField;
            }
            set {
                this.userIsAuthenticatedField = value;
            }
        }
        
        /// <remarks/>
        public string[] ADAttributesReturnValue {
            get {
                return this.aDAttributesReturnValueField;
            }
            set {
                this.aDAttributesReturnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS")]
    public partial class WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsReturnObj {
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        private bool userIsAuthenticatedField;
        
        private string userWSUIDField;
        
        private string userDisplayNameField;
        
        private string userFullNameField;
        
        private string userLastNameField;
        
        private string userFirstNameField;
        
        private string userEmailField;
        
        private bool userIsInAllGroupsIndField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsAuthenticated {
            get {
                return this.userIsAuthenticatedField;
            }
            set {
                this.userIsAuthenticatedField = value;
            }
        }
        
        /// <remarks/>
        public string UserWSUID {
            get {
                return this.userWSUIDField;
            }
            set {
                this.userWSUIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserDisplayName {
            get {
                return this.userDisplayNameField;
            }
            set {
                this.userDisplayNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserLastName {
            get {
                return this.userLastNameField;
            }
            set {
                this.userLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserFirstName {
            get {
                return this.userFirstNameField;
            }
            set {
                this.userFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserEmail {
            get {
                return this.userEmailField;
            }
            set {
                this.userEmailField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsInAllGroupsInd {
            get {
                return this.userIsInAllGroupsIndField;
            }
            set {
                this.userIsInAllGroupsIndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS")]
    public partial class WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsReturnObj {
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        private bool userIsAuthenticatedField;
        
        private string userWSUIDField;
        
        private string userDisplayNameField;
        
        private string userFullNameField;
        
        private string userLastNameField;
        
        private string userFirstNameField;
        
        private string userEmailField;
        
        private bool userIsInAnyGroupIndField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsAuthenticated {
            get {
                return this.userIsAuthenticatedField;
            }
            set {
                this.userIsAuthenticatedField = value;
            }
        }
        
        /// <remarks/>
        public string UserWSUID {
            get {
                return this.userWSUIDField;
            }
            set {
                this.userWSUIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserDisplayName {
            get {
                return this.userDisplayNameField;
            }
            set {
                this.userDisplayNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserLastName {
            get {
                return this.userLastNameField;
            }
            set {
                this.userLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserFirstName {
            get {
                return this.userFirstNameField;
            }
            set {
                this.userFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserEmail {
            get {
                return this.userEmailField;
            }
            set {
                this.userEmailField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsInAnyGroupInd {
            get {
                return this.userIsInAnyGroupIndField;
            }
            set {
                this.userIsInAnyGroupIndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS")]
    public partial class WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsReturnObj {
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        private bool userIsAuthenticatedField;
        
        private string userWSUIDField;
        
        private string userDisplayNameField;
        
        private string userFullNameField;
        
        private string userLastNameField;
        
        private string userFirstNameField;
        
        private string userEmailField;
        
        private string userGroupMembershipsField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsAuthenticated {
            get {
                return this.userIsAuthenticatedField;
            }
            set {
                this.userIsAuthenticatedField = value;
            }
        }
        
        /// <remarks/>
        public string UserWSUID {
            get {
                return this.userWSUIDField;
            }
            set {
                this.userWSUIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserDisplayName {
            get {
                return this.userDisplayNameField;
            }
            set {
                this.userDisplayNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserLastName {
            get {
                return this.userLastNameField;
            }
            set {
                this.userLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserFirstName {
            get {
                return this.userFirstNameField;
            }
            set {
                this.userFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserEmail {
            get {
                return this.userEmailField;
            }
            set {
                this.userEmailField = value;
            }
        }
        
        /// <remarks/>
        public string UserGroupMemberships {
            get {
                return this.userGroupMembershipsField;
            }
            set {
                this.userGroupMembershipsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS")]
    public partial class WSUAuthenticateUserIsInAllADGroupsReturnObj {
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        private bool userIsAuthenticatedField;
        
        private bool userIsInAllGroupsIndField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsAuthenticated {
            get {
                return this.userIsAuthenticatedField;
            }
            set {
                this.userIsAuthenticatedField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsInAllGroupsInd {
            get {
                return this.userIsInAllGroupsIndField;
            }
            set {
                this.userIsInAllGroupsIndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS")]
    public partial class WSUAuthenticateUserIsInAnyADGroupsReturnObj {
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        private bool userIsAuthenticatedField;
        
        private bool userIsInAnyGroupsIndField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsAuthenticated {
            get {
                return this.userIsAuthenticatedField;
            }
            set {
                this.userIsAuthenticatedField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsInAnyGroupsInd {
            get {
                return this.userIsInAnyGroupsIndField;
            }
            set {
                this.userIsInAnyGroupsIndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS")]
    public partial class WSUAuthenticateUserGetADGroupMembershipsReturnObj {
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        private bool userIsAuthenticatedField;
        
        private string userGroupMembershipsField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsAuthenticated {
            get {
                return this.userIsAuthenticatedField;
            }
            set {
                this.userIsAuthenticatedField = value;
            }
        }
        
        /// <remarks/>
        public string UserGroupMemberships {
            get {
                return this.userGroupMembershipsField;
            }
            set {
                this.userGroupMembershipsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it.wsu.edu/WSUADAuthenticateUser_WS/WSUADAuthenticateUser_WS")]
    public partial class WSUAuthenticateUserGetADIdentityAttributesReturnObj {
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        private bool userIsAuthenticatedField;
        
        private string userWSUIDField;
        
        private string userDisplayNameField;
        
        private string userFullNameField;
        
        private string userLastNameField;
        
        private string userFirstNameField;
        
        private string userEmailField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool UserIsAuthenticated {
            get {
                return this.userIsAuthenticatedField;
            }
            set {
                this.userIsAuthenticatedField = value;
            }
        }
        
        /// <remarks/>
        public string UserWSUID {
            get {
                return this.userWSUIDField;
            }
            set {
                this.userWSUIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserDisplayName {
            get {
                return this.userDisplayNameField;
            }
            set {
                this.userDisplayNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserLastName {
            get {
                return this.userLastNameField;
            }
            set {
                this.userLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserFirstName {
            get {
                return this.userFirstNameField;
            }
            set {
                this.userFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserEmail {
            get {
                return this.userEmailField;
            }
            set {
                this.userEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WSUAuthenticateUserCompletedEventHandler(object sender, WSUAuthenticateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSUAuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSUAuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUAuthenticateUserReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUAuthenticateUserReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WSUAuthenticateUserGetADIdentityAttributesCompletedEventHandler(object sender, WSUAuthenticateUserGetADIdentityAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSUAuthenticateUserGetADIdentityAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSUAuthenticateUserGetADIdentityAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUAuthenticateUserGetADIdentityAttributesReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUAuthenticateUserGetADIdentityAttributesReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WSUAuthenticateUserGetADGroupMembershipsCompletedEventHandler(object sender, WSUAuthenticateUserGetADGroupMembershipsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSUAuthenticateUserGetADGroupMembershipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSUAuthenticateUserGetADGroupMembershipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUAuthenticateUserGetADGroupMembershipsReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUAuthenticateUserGetADGroupMembershipsReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WSUAuthenticateUserIsInAnyADGroupsCompletedEventHandler(object sender, WSUAuthenticateUserIsInAnyADGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSUAuthenticateUserIsInAnyADGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSUAuthenticateUserIsInAnyADGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUAuthenticateUserIsInAnyADGroupsReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUAuthenticateUserIsInAnyADGroupsReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WSUAuthenticateUserIsInAllADGroupsCompletedEventHandler(object sender, WSUAuthenticateUserIsInAllADGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSUAuthenticateUserIsInAllADGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSUAuthenticateUserIsInAllADGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUAuthenticateUserIsInAllADGroupsReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUAuthenticateUserIsInAllADGroupsReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsCompletedEventHandler(object sender, WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUAuthenticateUserGetADIdentityAttributesGetADGroupMembershipsReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsCompletedEventHandler(object sender, WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUAuthenticateUserGetADIdentityAttributesIsInAnyADGroupsReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsCompletedEventHandler(object sender, WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUAuthenticateUserGetADIdentityAttributesIsInAllADGroupsReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WSUAuthenticateUserGetAnyGivenADAttributesCompletedEventHandler(object sender, WSUAuthenticateUserGetAnyGivenADAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSUAuthenticateUserGetAnyGivenADAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSUAuthenticateUserGetAnyGivenADAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUAuthenticateUserGetAnyGivenADAttributesReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUAuthenticateUserGetAnyGivenADAttributesReturnObj)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591